name: dependency-review
on:
  workflow_call:

permissions:
      pull-requests: write
       # only required for workflows in private repositories
      actions: read
      contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
   
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4.3.3
        with:
          comment-summary-in-pr: true
          fail-on-severity: low
          vulnerability-check: true
          show-openssf-scorecard: true
